"""init migration

Revision ID: b0e256050925
Revises: 
Create Date: 2025-07-28 14:13:49.778660

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b0e256050925'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create users table
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('hashed_password', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    
    # Create puskesmas table
    op.create_table('puskesmas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nama', sa.String(), nullable=False),
        sa.Column('kode', sa.String(), nullable=True),
        sa.Column('alamat', sa.String(), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=False),
        sa.Column('longitude', sa.Float(), nullable=False),
        sa.Column('kecamatan', sa.String(), nullable=False),
        sa.Column('kabupaten', sa.String(), nullable=False),
        sa.Column('provinsi', sa.String(), nullable=False),
        sa.Column('kapasitas', sa.Integer(), nullable=True),
        sa.Column('radius_cover', sa.Float(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_puskesmas_id'), 'puskesmas', ['id'], unique=False)
    op.create_index(op.f('ix_puskesmas_kode'), 'puskesmas', ['kode'], unique=True)
    
    # Create populations table
    op.create_table('populations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('kecamatan', sa.String(), nullable=False),
        sa.Column('kabupaten', sa.String(), nullable=False),
        sa.Column('provinsi', sa.String(), nullable=False),
        sa.Column('jumlah_penduduk', sa.Integer(), nullable=True),
        sa.Column('luas_wilayah', sa.Float(), nullable=True),
        sa.Column('kepadatan', sa.Float(), nullable=True),
        sa.Column('tingkat_kemiskinan', sa.Float(), nullable=True),
        sa.Column('latitude_center', sa.Float(), nullable=True),
        sa.Column('longitude_center', sa.Float(), nullable=True),
        sa.Column('tahun_data', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_populations_id'), 'populations', ['id'], unique=False)
    op.create_index(op.f('ix_populations_kecamatan'), 'populations', ['kecamatan'], unique=False)
    op.create_index(op.f('ix_populations_kabupaten'), 'populations', ['kabupaten'], unique=False)
    op.create_index(op.f('ix_populations_provinsi'), 'populations', ['provinsi'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_populations_provinsi'), table_name='populations')
    op.drop_index(op.f('ix_populations_kabupaten'), table_name='populations')
    op.drop_index(op.f('ix_populations_kecamatan'), table_name='populations')
    op.drop_index(op.f('ix_populations_id'), table_name='populations')
    op.drop_table('populations')
    op.drop_index(op.f('ix_puskesmas_kode'), table_name='puskesmas')
    op.drop_index(op.f('ix_puskesmas_id'), table_name='puskesmas')
    op.drop_table('puskesmas')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ### 