"""initial migration

Revision ID: c3a2c4c74f78
Revises: b0e256050925
Create Date: 2025-07-29 16:24:40.560109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a2c4c74f78'
down_revision = 'b0e256050925'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 