"""added new reasoning field

Revision ID: b490bd1de10b
Revises: 3eb70e20a9de
Create Date: 2025-08-02 23:53:21.940528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b490bd1de10b'
down_revision = '3eb70e20a9de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('population_points_raw')
    # op.drop_table('spatial_ref_sys')
    # op.drop_table('health_facilities_staging')
    # op.drop_table('population_points_staging')
    op.add_column('simulation_results', sa.Column('automated_reasoning', sa.Text(), nullable=True))
    # op.create_index(op.f('ix_subdistricts_pum_code'), 'subdistricts', ['pum_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subdistricts_pum_code'), table_name='subdistricts')
    op.drop_column('simulation_results', 'automated_reasoning')
    op.create_table('population_points_staging',
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('population_count', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('health_facilities_staging',
    sa.Column('kode_pusk', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nama_puskesmas', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('jenis_puskesmas', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.create_table('population_points_raw',
    sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('population_count', sa.NUMERIC(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ### 